### ISSUE TITLE
This template is invaild

### ISSUE THREAD

**Issue by Danjhop4** [gradle/gradle-issue-reproducer#7]

**Comment by Danjhop4** [comment]
You can’t use this but they won’t except anything but this

**Comment by ov7a** [comment]
@Danjhop4 Hello. I believe you are referencing 
* https://github.com/gradle/gradle/issues/26191

You are wrong about  "they won’t except anything but this". We do accept any type of reproducer if it properly represents the issue. The problem with the issue was you not giving us enough information about the problem.
